---
- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'

- name: enabling modules
  lineinfile:
    dest: /etc/php/5.6/apache2/php.ini
    backrefs: yes
    regexp: '{{item.regexp}}'
    line: '{{item.line}}'
  with_items: '{{php.config}}'
  when: php.config is defined
