---
- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/5.6/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache cli
  lineinfile: dest=/etc/php/5.6/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'

- name: enabling modules
  lineinfile:
    dest: /etc/php/5.6/cli/php.ini
    backrefs: yes
    regexp: '{{item.regexp}}'
    line: '{{item.line}}'
  with_items: '{{php.config}}'
  when: php.config is defined
